# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-21 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ber', models.IntegerField(default=1)),
                ('sp', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'lq_cart',
            },
        ),
        migrations.CreateModel(
            name='OtherPro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('concent', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'lq_Other',
            },
        ),
        migrations.CreateModel(
            name='ProModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=255)),
                ('img1', models.CharField(max_length=255)),
                ('img2', models.CharField(max_length=255)),
                ('img3', models.CharField(max_length=255)),
                ('img4', models.CharField(max_length=255)),
                ('img5', models.CharField(max_length=255)),
                ('img6', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('concent', models.CharField(max_length=100)),
                ('concent1', models.CharField(max_length=100)),
                ('concent2', models.CharField(max_length=100)),
                ('concent3', models.CharField(max_length=100)),
                ('concent4', models.CharField(max_length=100)),
                ('concent5', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'lq_pro',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('psd', models.CharField(max_length=100)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'lq_user',
            },
        ),
        migrations.CreateModel(
            name='WheelModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lq_wheel',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.ProModel'),
        ),
    ]
