# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-22 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_cart2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='sp',
        ),
        migrations.AddField(
            model_name='cart',
            name='is_select',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.User'),
        ),
    ]
