# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-27 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20190727_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='order_time',
            field=models.DateTimeField(),
        ),
    ]
