# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-27 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20190727_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
